// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: proto/taskList/taskList.proto

package tasklistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_OPEN        TaskStatus = 1
	TaskStatus_TASK_STATUS_ASSIGNED    TaskStatus = 2
	TaskStatus_TASK_STATUS_CLOSED      TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_OPEN",
		2: "TASK_STATUS_ASSIGNED",
		3: "TASK_STATUS_CLOSED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_OPEN":        1,
		"TASK_STATUS_ASSIGNED":    2,
		"TASK_STATUS_CLOSED":      3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_taskList_taskList_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_taskList_taskList_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{0}
}

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{0}
}

func (x *AddUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AddUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserResponse) Reset() {
	*x = AddUserResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserResponse) ProtoMessage() {}

func (x *AddUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserResponse.ProtoReflect.Descriptor instead.
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{1}
}

func (x *AddUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserRequest) Reset() {
	*x = ChangeUserRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserRequest) ProtoMessage() {}

func (x *ChangeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ChangeUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserResponse) Reset() {
	*x = ChangeUserResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserResponse) ProtoMessage() {}

func (x *ChangeUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TgId          int64                  `protobuf:"varint,2,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *CreateTaskRequest) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{9}
}

func (x *GetTasksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{10}
}

func (x *GetTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ChangeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTaskRequest) Reset() {
	*x = ChangeTaskRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTaskRequest) ProtoMessage() {}

func (x *ChangeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTaskRequest.ProtoReflect.Descriptor instead.
func (*ChangeTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ChangeTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeTaskRequest) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

type ChangeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTaskResponse) Reset() {
	*x = ChangeTaskResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTaskResponse) ProtoMessage() {}

func (x *ChangeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTaskResponse.ProtoReflect.Descriptor instead.
func (*ChangeTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type AssignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskRequest) Reset() {
	*x = AssignTaskRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskRequest) ProtoMessage() {}

func (x *AssignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{13}
}

func (x *AssignTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AssignTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskResponse) Reset() {
	*x = AssignTaskResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskResponse) ProtoMessage() {}

func (x *AssignTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskResponse.ProtoReflect.Descriptor instead.
func (*AssignTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{14}
}

func (x *AssignTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CloseTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTaskRequest) Reset() {
	*x = CloseTaskRequest{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTaskRequest) ProtoMessage() {}

func (x *CloseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTaskRequest.ProtoReflect.Descriptor instead.
func (*CloseTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{15}
}

func (x *CloseTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CloseTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CloseTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTaskResponse) Reset() {
	*x = CloseTaskResponse{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTaskResponse) ProtoMessage() {}

func (x *CloseTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTaskResponse.ProtoReflect.Descriptor instead.
func (*CloseTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{16}
}

func (x *CloseTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=taskList.v1.TaskStatus" json:"status,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_taskList_taskList_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskList_taskList_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_taskList_taskList_proto_rawDescGZIP(), []int{17}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Task) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

var File_proto_taskList_taskList_proto protoreflect.FileDescriptor

const file_proto_taskList_taskList_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/taskList/taskList.proto\x12\vtaskList.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x0eAddUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"8\n" +
	"\x0fAddUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.taskList.v1.UserR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x0fGetUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.taskList.v1.UserR\x04user\",\n" +
	"\x11ChangeUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x12ChangeUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.taskList.v1.UserR\x04user\"d\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x13\n" +
	"\x05tg_id\x18\x02 \x01(\x03R\x04tgId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"s\n" +
	"\x11CreateTaskRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x121\n" +
	"\x06due_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\";\n" +
	"\x12CreateTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskList.v1.TaskR\x04task\"*\n" +
	"\x0fGetTasksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x10GetTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.taskList.v1.TaskR\x05tasks\"x\n" +
	"\x11ChangeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x121\n" +
	"\x06due_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\";\n" +
	"\x12ChangeTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskList.v1.TaskR\x04task\"E\n" +
	"\x11AssignTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	"\x12AssignTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskList.v1.TaskR\x04task\"D\n" +
	"\x10CloseTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\":\n" +
	"\x11CloseTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskList.v1.TaskR\x04task\"\xb0\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.taskList.v1.TaskStatusR\x06status\x121\n" +
	"\x06due_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt*q\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_STATUS_OPEN\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_ASSIGNED\x10\x02\x12\x16\n" +
	"\x12TASK_STATUS_CLOSED\x10\x032\xee\x01\n" +
	"\vUserService\x12F\n" +
	"\aAddUser\x12\x1b.taskList.v1.AddUserRequest\x1a\x1c.taskList.v1.AddUserResponse\"\x00\x12F\n" +
	"\aGetUser\x12\x1b.taskList.v1.GetUserRequest\x1a\x1c.taskList.v1.GetUserResponse\"\x00\x12O\n" +
	"\n" +
	"ChangeUser\x12\x1e.taskList.v1.ChangeUserRequest\x1a\x1f.taskList.v1.ChangeUserResponse\"\x002\x99\x03\n" +
	"\vTaskService\x12O\n" +
	"\n" +
	"CreateTask\x12\x1e.taskList.v1.CreateTaskRequest\x1a\x1f.taskList.v1.CreateTaskResponse\"\x00\x12I\n" +
	"\bGetTasks\x12\x1c.taskList.v1.GetTasksRequest\x1a\x1d.taskList.v1.GetTasksResponse\"\x00\x12O\n" +
	"\n" +
	"ChangeTask\x12\x1e.taskList.v1.ChangeTaskRequest\x1a\x1f.taskList.v1.ChangeTaskResponse\"\x00\x12O\n" +
	"\n" +
	"AssignTask\x12\x1e.taskList.v1.AssignTaskRequest\x1a\x1f.taskList.v1.AssignTaskResponse\"\x00\x12L\n" +
	"\tCloseTask\x12\x1d.taskList.v1.CloseTaskRequest\x1a\x1e.taskList.v1.CloseTaskResponse\"\x00B<Z:github.com/lirprocs/gRPCTaskList/pb/tasklist/v1;tasklistpbb\x06proto3"

var (
	file_proto_taskList_taskList_proto_rawDescOnce sync.Once
	file_proto_taskList_taskList_proto_rawDescData []byte
)

func file_proto_taskList_taskList_proto_rawDescGZIP() []byte {
	file_proto_taskList_taskList_proto_rawDescOnce.Do(func() {
		file_proto_taskList_taskList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_taskList_taskList_proto_rawDesc), len(file_proto_taskList_taskList_proto_rawDesc)))
	})
	return file_proto_taskList_taskList_proto_rawDescData
}

var file_proto_taskList_taskList_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_taskList_taskList_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_taskList_taskList_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: taskList.v1.TaskStatus
	(*AddUserRequest)(nil),        // 1: taskList.v1.AddUserRequest
	(*AddUserResponse)(nil),       // 2: taskList.v1.AddUserResponse
	(*GetUserRequest)(nil),        // 3: taskList.v1.GetUserRequest
	(*GetUserResponse)(nil),       // 4: taskList.v1.GetUserResponse
	(*ChangeUserRequest)(nil),     // 5: taskList.v1.ChangeUserRequest
	(*ChangeUserResponse)(nil),    // 6: taskList.v1.ChangeUserResponse
	(*User)(nil),                  // 7: taskList.v1.User
	(*CreateTaskRequest)(nil),     // 8: taskList.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 9: taskList.v1.CreateTaskResponse
	(*GetTasksRequest)(nil),       // 10: taskList.v1.GetTasksRequest
	(*GetTasksResponse)(nil),      // 11: taskList.v1.GetTasksResponse
	(*ChangeTaskRequest)(nil),     // 12: taskList.v1.ChangeTaskRequest
	(*ChangeTaskResponse)(nil),    // 13: taskList.v1.ChangeTaskResponse
	(*AssignTaskRequest)(nil),     // 14: taskList.v1.AssignTaskRequest
	(*AssignTaskResponse)(nil),    // 15: taskList.v1.AssignTaskResponse
	(*CloseTaskRequest)(nil),      // 16: taskList.v1.CloseTaskRequest
	(*CloseTaskResponse)(nil),     // 17: taskList.v1.CloseTaskResponse
	(*Task)(nil),                  // 18: taskList.v1.Task
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_proto_taskList_taskList_proto_depIdxs = []int32{
	7,  // 0: taskList.v1.AddUserResponse.user:type_name -> taskList.v1.User
	7,  // 1: taskList.v1.GetUserResponse.user:type_name -> taskList.v1.User
	7,  // 2: taskList.v1.ChangeUserResponse.user:type_name -> taskList.v1.User
	19, // 3: taskList.v1.CreateTaskRequest.due_at:type_name -> google.protobuf.Timestamp
	18, // 4: taskList.v1.CreateTaskResponse.task:type_name -> taskList.v1.Task
	18, // 5: taskList.v1.GetTasksResponse.tasks:type_name -> taskList.v1.Task
	19, // 6: taskList.v1.ChangeTaskRequest.due_at:type_name -> google.protobuf.Timestamp
	18, // 7: taskList.v1.ChangeTaskResponse.task:type_name -> taskList.v1.Task
	18, // 8: taskList.v1.AssignTaskResponse.task:type_name -> taskList.v1.Task
	18, // 9: taskList.v1.CloseTaskResponse.task:type_name -> taskList.v1.Task
	0,  // 10: taskList.v1.Task.status:type_name -> taskList.v1.TaskStatus
	19, // 11: taskList.v1.Task.due_at:type_name -> google.protobuf.Timestamp
	1,  // 12: taskList.v1.UserService.AddUser:input_type -> taskList.v1.AddUserRequest
	3,  // 13: taskList.v1.UserService.GetUser:input_type -> taskList.v1.GetUserRequest
	5,  // 14: taskList.v1.UserService.ChangeUser:input_type -> taskList.v1.ChangeUserRequest
	8,  // 15: taskList.v1.TaskService.CreateTask:input_type -> taskList.v1.CreateTaskRequest
	10, // 16: taskList.v1.TaskService.GetTasks:input_type -> taskList.v1.GetTasksRequest
	12, // 17: taskList.v1.TaskService.ChangeTask:input_type -> taskList.v1.ChangeTaskRequest
	14, // 18: taskList.v1.TaskService.AssignTask:input_type -> taskList.v1.AssignTaskRequest
	16, // 19: taskList.v1.TaskService.CloseTask:input_type -> taskList.v1.CloseTaskRequest
	2,  // 20: taskList.v1.UserService.AddUser:output_type -> taskList.v1.AddUserResponse
	4,  // 21: taskList.v1.UserService.GetUser:output_type -> taskList.v1.GetUserResponse
	6,  // 22: taskList.v1.UserService.ChangeUser:output_type -> taskList.v1.ChangeUserResponse
	9,  // 23: taskList.v1.TaskService.CreateTask:output_type -> taskList.v1.CreateTaskResponse
	11, // 24: taskList.v1.TaskService.GetTasks:output_type -> taskList.v1.GetTasksResponse
	13, // 25: taskList.v1.TaskService.ChangeTask:output_type -> taskList.v1.ChangeTaskResponse
	15, // 26: taskList.v1.TaskService.AssignTask:output_type -> taskList.v1.AssignTaskResponse
	17, // 27: taskList.v1.TaskService.CloseTask:output_type -> taskList.v1.CloseTaskResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_taskList_taskList_proto_init() }
func file_proto_taskList_taskList_proto_init() {
	if File_proto_taskList_taskList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_taskList_taskList_proto_rawDesc), len(file_proto_taskList_taskList_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_taskList_taskList_proto_goTypes,
		DependencyIndexes: file_proto_taskList_taskList_proto_depIdxs,
		EnumInfos:         file_proto_taskList_taskList_proto_enumTypes,
		MessageInfos:      file_proto_taskList_taskList_proto_msgTypes,
	}.Build()
	File_proto_taskList_taskList_proto = out.File
	file_proto_taskList_taskList_proto_goTypes = nil
	file_proto_taskList_taskList_proto_depIdxs = nil
}
